/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewsroomRouteImport } from './routes/newsroom'
import { Route as LaunchesRouteImport } from './routes/launches'
import { Route as InvestorRelationsRouteImport } from './routes/investor-relations'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as CustomerServiceRouteImport } from './routes/customer-service'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompletedRouteImport } from './routes/completed'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BrokersRouteImport } from './routes/brokers'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunitiesIndexRouteImport } from './routes/communities.index'
import { Route as PropertiesVillasRouteImport } from './routes/properties.villas'
import { Route as PropertiesTownhousesRouteImport } from './routes/properties.townhouses'
import { Route as PropertiesHospitalityRouteImport } from './routes/properties.hospitality'
import { Route as PropertiesCommercialRouteImport } from './routes/properties.commercial'
import { Route as PropertiesApartmentsRouteImport } from './routes/properties.apartments'
import { Route as LaunchesSlugRouteImport } from './routes/launches.$slug'
import { Route as CompletedSlugRouteImport } from './routes/completed.$slug'
import { Route as CommunitiesSlugRouteImport } from './routes/communities.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsroomRoute = NewsroomRouteImport.update({
  id: '/newsroom',
  path: '/newsroom',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchesRoute = LaunchesRouteImport.update({
  id: '/launches',
  path: '/launches',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorRelationsRoute = InvestorRelationsRouteImport.update({
  id: '/investor-relations',
  path: '/investor-relations',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerServiceRoute = CustomerServiceRouteImport.update({
  id: '/customer-service',
  path: '/customer-service',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletedRoute = CompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokersRoute = BrokersRouteImport.update({
  id: '/brokers',
  path: '/brokers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesIndexRoute = CommunitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunitiesRoute,
} as any)
const PropertiesVillasRoute = PropertiesVillasRouteImport.update({
  id: '/properties/villas',
  path: '/properties/villas',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesTownhousesRoute = PropertiesTownhousesRouteImport.update({
  id: '/properties/townhouses',
  path: '/properties/townhouses',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesHospitalityRoute = PropertiesHospitalityRouteImport.update({
  id: '/properties/hospitality',
  path: '/properties/hospitality',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesCommercialRoute = PropertiesCommercialRouteImport.update({
  id: '/properties/commercial',
  path: '/properties/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesApartmentsRoute = PropertiesApartmentsRouteImport.update({
  id: '/properties/apartments',
  path: '/properties/apartments',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchesSlugRoute = LaunchesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LaunchesRoute,
} as any)
const CompletedSlugRoute = CompletedSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CompletedRoute,
} as any)
const CommunitiesSlugRoute = CommunitiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CommunitiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/brokers': typeof BrokersRoute
  '/careers': typeof CareersRoute
  '/communities': typeof CommunitiesRouteWithChildren
  '/completed': typeof CompletedRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/customer-service': typeof CustomerServiceRoute
  '/faqs': typeof FaqsRoute
  '/investor-relations': typeof InvestorRelationsRoute
  '/launches': typeof LaunchesRouteWithChildren
  '/newsroom': typeof NewsroomRoute
  '/privacy': typeof PrivacyRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/communities/$slug': typeof CommunitiesSlugRoute
  '/completed/$slug': typeof CompletedSlugRoute
  '/launches/$slug': typeof LaunchesSlugRoute
  '/properties/apartments': typeof PropertiesApartmentsRoute
  '/properties/commercial': typeof PropertiesCommercialRoute
  '/properties/hospitality': typeof PropertiesHospitalityRoute
  '/properties/townhouses': typeof PropertiesTownhousesRoute
  '/properties/villas': typeof PropertiesVillasRoute
  '/communities/': typeof CommunitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/brokers': typeof BrokersRoute
  '/careers': typeof CareersRoute
  '/completed': typeof CompletedRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/customer-service': typeof CustomerServiceRoute
  '/faqs': typeof FaqsRoute
  '/investor-relations': typeof InvestorRelationsRoute
  '/launches': typeof LaunchesRouteWithChildren
  '/newsroom': typeof NewsroomRoute
  '/privacy': typeof PrivacyRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/communities/$slug': typeof CommunitiesSlugRoute
  '/completed/$slug': typeof CompletedSlugRoute
  '/launches/$slug': typeof LaunchesSlugRoute
  '/properties/apartments': typeof PropertiesApartmentsRoute
  '/properties/commercial': typeof PropertiesCommercialRoute
  '/properties/hospitality': typeof PropertiesHospitalityRoute
  '/properties/townhouses': typeof PropertiesTownhousesRoute
  '/properties/villas': typeof PropertiesVillasRoute
  '/communities': typeof CommunitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/brokers': typeof BrokersRoute
  '/careers': typeof CareersRoute
  '/communities': typeof CommunitiesRouteWithChildren
  '/completed': typeof CompletedRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/customer-service': typeof CustomerServiceRoute
  '/faqs': typeof FaqsRoute
  '/investor-relations': typeof InvestorRelationsRoute
  '/launches': typeof LaunchesRouteWithChildren
  '/newsroom': typeof NewsroomRoute
  '/privacy': typeof PrivacyRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/communities/$slug': typeof CommunitiesSlugRoute
  '/completed/$slug': typeof CompletedSlugRoute
  '/launches/$slug': typeof LaunchesSlugRoute
  '/properties/apartments': typeof PropertiesApartmentsRoute
  '/properties/commercial': typeof PropertiesCommercialRoute
  '/properties/hospitality': typeof PropertiesHospitalityRoute
  '/properties/townhouses': typeof PropertiesTownhousesRoute
  '/properties/villas': typeof PropertiesVillasRoute
  '/communities/': typeof CommunitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/brokers'
    | '/careers'
    | '/communities'
    | '/completed'
    | '/contact'
    | '/cookies'
    | '/customer-service'
    | '/faqs'
    | '/investor-relations'
    | '/launches'
    | '/newsroom'
    | '/privacy'
    | '/sustainability'
    | '/terms'
    | '/communities/$slug'
    | '/completed/$slug'
    | '/launches/$slug'
    | '/properties/apartments'
    | '/properties/commercial'
    | '/properties/hospitality'
    | '/properties/townhouses'
    | '/properties/villas'
    | '/communities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/brokers'
    | '/careers'
    | '/completed'
    | '/contact'
    | '/cookies'
    | '/customer-service'
    | '/faqs'
    | '/investor-relations'
    | '/launches'
    | '/newsroom'
    | '/privacy'
    | '/sustainability'
    | '/terms'
    | '/communities/$slug'
    | '/completed/$slug'
    | '/launches/$slug'
    | '/properties/apartments'
    | '/properties/commercial'
    | '/properties/hospitality'
    | '/properties/townhouses'
    | '/properties/villas'
    | '/communities'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/brokers'
    | '/careers'
    | '/communities'
    | '/completed'
    | '/contact'
    | '/cookies'
    | '/customer-service'
    | '/faqs'
    | '/investor-relations'
    | '/launches'
    | '/newsroom'
    | '/privacy'
    | '/sustainability'
    | '/terms'
    | '/communities/$slug'
    | '/completed/$slug'
    | '/launches/$slug'
    | '/properties/apartments'
    | '/properties/commercial'
    | '/properties/hospitality'
    | '/properties/townhouses'
    | '/properties/villas'
    | '/communities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BrokersRoute: typeof BrokersRoute
  CareersRoute: typeof CareersRoute
  CommunitiesRoute: typeof CommunitiesRouteWithChildren
  CompletedRoute: typeof CompletedRouteWithChildren
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  CustomerServiceRoute: typeof CustomerServiceRoute
  FaqsRoute: typeof FaqsRoute
  InvestorRelationsRoute: typeof InvestorRelationsRoute
  LaunchesRoute: typeof LaunchesRouteWithChildren
  NewsroomRoute: typeof NewsroomRoute
  PrivacyRoute: typeof PrivacyRoute
  SustainabilityRoute: typeof SustainabilityRoute
  TermsRoute: typeof TermsRoute
  PropertiesApartmentsRoute: typeof PropertiesApartmentsRoute
  PropertiesCommercialRoute: typeof PropertiesCommercialRoute
  PropertiesHospitalityRoute: typeof PropertiesHospitalityRoute
  PropertiesTownhousesRoute: typeof PropertiesTownhousesRoute
  PropertiesVillasRoute: typeof PropertiesVillasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsroom': {
      id: '/newsroom'
      path: '/newsroom'
      fullPath: '/newsroom'
      preLoaderRoute: typeof NewsroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launches': {
      id: '/launches'
      path: '/launches'
      fullPath: '/launches'
      preLoaderRoute: typeof LaunchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor-relations': {
      id: '/investor-relations'
      path: '/investor-relations'
      fullPath: '/investor-relations'
      preLoaderRoute: typeof InvestorRelationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-service': {
      id: '/customer-service'
      path: '/customer-service'
      fullPath: '/customer-service'
      preLoaderRoute: typeof CustomerServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completed': {
      id: '/completed'
      path: '/completed'
      fullPath: '/completed'
      preLoaderRoute: typeof CompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brokers': {
      id: '/brokers'
      path: '/brokers'
      fullPath: '/brokers'
      preLoaderRoute: typeof BrokersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/': {
      id: '/communities/'
      path: '/'
      fullPath: '/communities/'
      preLoaderRoute: typeof CommunitiesIndexRouteImport
      parentRoute: typeof CommunitiesRoute
    }
    '/properties/villas': {
      id: '/properties/villas'
      path: '/properties/villas'
      fullPath: '/properties/villas'
      preLoaderRoute: typeof PropertiesVillasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/townhouses': {
      id: '/properties/townhouses'
      path: '/properties/townhouses'
      fullPath: '/properties/townhouses'
      preLoaderRoute: typeof PropertiesTownhousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/hospitality': {
      id: '/properties/hospitality'
      path: '/properties/hospitality'
      fullPath: '/properties/hospitality'
      preLoaderRoute: typeof PropertiesHospitalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/commercial': {
      id: '/properties/commercial'
      path: '/properties/commercial'
      fullPath: '/properties/commercial'
      preLoaderRoute: typeof PropertiesCommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/apartments': {
      id: '/properties/apartments'
      path: '/properties/apartments'
      fullPath: '/properties/apartments'
      preLoaderRoute: typeof PropertiesApartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launches/$slug': {
      id: '/launches/$slug'
      path: '/$slug'
      fullPath: '/launches/$slug'
      preLoaderRoute: typeof LaunchesSlugRouteImport
      parentRoute: typeof LaunchesRoute
    }
    '/completed/$slug': {
      id: '/completed/$slug'
      path: '/$slug'
      fullPath: '/completed/$slug'
      preLoaderRoute: typeof CompletedSlugRouteImport
      parentRoute: typeof CompletedRoute
    }
    '/communities/$slug': {
      id: '/communities/$slug'
      path: '/$slug'
      fullPath: '/communities/$slug'
      preLoaderRoute: typeof CommunitiesSlugRouteImport
      parentRoute: typeof CommunitiesRoute
    }
  }
}

interface CommunitiesRouteChildren {
  CommunitiesSlugRoute: typeof CommunitiesSlugRoute
  CommunitiesIndexRoute: typeof CommunitiesIndexRoute
}

const CommunitiesRouteChildren: CommunitiesRouteChildren = {
  CommunitiesSlugRoute: CommunitiesSlugRoute,
  CommunitiesIndexRoute: CommunitiesIndexRoute,
}

const CommunitiesRouteWithChildren = CommunitiesRoute._addFileChildren(
  CommunitiesRouteChildren,
)

interface CompletedRouteChildren {
  CompletedSlugRoute: typeof CompletedSlugRoute
}

const CompletedRouteChildren: CompletedRouteChildren = {
  CompletedSlugRoute: CompletedSlugRoute,
}

const CompletedRouteWithChildren = CompletedRoute._addFileChildren(
  CompletedRouteChildren,
)

interface LaunchesRouteChildren {
  LaunchesSlugRoute: typeof LaunchesSlugRoute
}

const LaunchesRouteChildren: LaunchesRouteChildren = {
  LaunchesSlugRoute: LaunchesSlugRoute,
}

const LaunchesRouteWithChildren = LaunchesRoute._addFileChildren(
  LaunchesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BrokersRoute: BrokersRoute,
  CareersRoute: CareersRoute,
  CommunitiesRoute: CommunitiesRouteWithChildren,
  CompletedRoute: CompletedRouteWithChildren,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  CustomerServiceRoute: CustomerServiceRoute,
  FaqsRoute: FaqsRoute,
  InvestorRelationsRoute: InvestorRelationsRoute,
  LaunchesRoute: LaunchesRouteWithChildren,
  NewsroomRoute: NewsroomRoute,
  PrivacyRoute: PrivacyRoute,
  SustainabilityRoute: SustainabilityRoute,
  TermsRoute: TermsRoute,
  PropertiesApartmentsRoute: PropertiesApartmentsRoute,
  PropertiesCommercialRoute: PropertiesCommercialRoute,
  PropertiesHospitalityRoute: PropertiesHospitalityRoute,
  PropertiesTownhousesRoute: PropertiesTownhousesRoute,
  PropertiesVillasRoute: PropertiesVillasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
